// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import (
	bbnclient "github.com/babylonlabs-io/babylon-staking-indexer/internal/clients/bbnclient"
	btccheckpointtypes "github.com/babylonlabs-io/babylon/x/btccheckpoint/types"

	context "context"

	coretypes "github.com/cometbft/cometbft/rpc/core/types"

	mock "github.com/stretchr/testify/mock"

	types "github.com/babylonlabs-io/babylon-staking-indexer/internal/types"
)

// BbnInterface is an autogenerated mock type for the BbnInterface type
type BbnInterface struct {
	mock.Mock
}

// GetAllStakingParams provides a mock function with given fields: ctx
func (_m *BbnInterface) GetAllStakingParams(ctx context.Context) (map[uint32]*bbnclient.StakingParams, *types.Error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllStakingParams")
	}

	var r0 map[uint32]*bbnclient.StakingParams
	var r1 *types.Error
	if rf, ok := ret.Get(0).(func(context.Context) (map[uint32]*bbnclient.StakingParams, *types.Error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[uint32]*bbnclient.StakingParams); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint32]*bbnclient.StakingParams)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) *types.Error); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Error)
		}
	}

	return r0, r1
}

// GetBlockResults provides a mock function with given fields: ctx, blockHeight
func (_m *BbnInterface) GetBlockResults(ctx context.Context, blockHeight int64) (*coretypes.ResultBlockResults, *types.Error) {
	ret := _m.Called(ctx, blockHeight)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockResults")
	}

	var r0 *coretypes.ResultBlockResults
	var r1 *types.Error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*coretypes.ResultBlockResults, *types.Error)); ok {
		return rf(ctx, blockHeight)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *coretypes.ResultBlockResults); ok {
		r0 = rf(ctx, blockHeight)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coretypes.ResultBlockResults)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) *types.Error); ok {
		r1 = rf(ctx, blockHeight)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Error)
		}
	}

	return r0, r1
}

// GetCheckpointParams provides a mock function with given fields: ctx
func (_m *BbnInterface) GetCheckpointParams(ctx context.Context) (*btccheckpointtypes.Params, *types.Error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckpointParams")
	}

	var r0 *btccheckpointtypes.Params
	var r1 *types.Error
	if rf, ok := ret.Get(0).(func(context.Context) (*btccheckpointtypes.Params, *types.Error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *btccheckpointtypes.Params); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*btccheckpointtypes.Params)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) *types.Error); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Error)
		}
	}

	return r0, r1
}

// GetLatestBlockNumber provides a mock function with given fields: ctx
func (_m *BbnInterface) GetLatestBlockNumber(ctx context.Context) (int64, *types.Error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlockNumber")
	}

	var r0 int64
	var r1 *types.Error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, *types.Error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) *types.Error); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Error)
		}
	}

	return r0, r1
}

// NewBbnInterface creates a new instance of BbnInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBbnInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BbnInterface {
	mock := &BbnInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
