version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - mnd
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 120
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - sloppyReassign
        - ifElseChain
        - sprintfQuotedString
        - exitAfterDefer
      enabled-tags:
        - diagnostic
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G115
    govet:
      enable:
        - nilness
    lll:
      line-length: 140
    misspell:
      locale: UK
    mnd:
      checks:
        - argument
        - case
        - return
      ignored-files:
        - e2etest/.+\.go$
      ignored-functions:
        - strings.SplitN
        - make
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustruct
          - funlen
          - gosec
          - lll
          - mnd
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
