db:
  username: root
  password: example
  address: "mongodb://indexer-mongodb:27017/?directConnection=true"
  db-name: babylon-staking-indexer
btc:
  disable-tls: true # use true for bitcoind as it does not support tls
  endpoint: 127.0.0.1:38332 # use port 18443 for bitcoind regtest
  estimate-mode: CONSERVATIVE # only needed by bitcoind
  net-params: signet  # use regtest for bitcoind as it does not support simnet
  username: K78L47aCp6NrcLnG0sTD8k5oaNZuwK1m
  password: YIr0Y7gMHPofvBDmZYmu2Cm0gR7OGz5x
  reconnect-attempts: 3
  btc-backend: bitcoind # {btcd, bitcoind}
  zmq-endpoint: tcp://127.0.0.1:29000  # use tcp://127.0.0.1:29000 if btc-backend is bitcoind
  zmq-seq-endpoint: tcp://127.0.0.1:29000
  zmq-block-endpoint: tcp://127.0.0.1:29000
  zmq-tx-endpoint: tcp://127.0.0.1:29000
bbn:
  rpc-addr: https://rpc.devnet.babylonlabs.io:443
  timeout: 30s
poller:
  param-polling-interval: 60s
  expiry-checker-polling-interval: 10s
  expired-delegations-limit: 100
queue:
  queue_user: user # can be replaced by values in .env file
  queue_password: password
  url: "localhost:5672"
  processing_timeout: 5 # 5 second
  msg_max_retry_attempts: 10
  requeue_delay_time: 300
  queue_type: quorum
metrics:
  host: 0.0.0.0
  port: 2112